# Hemos quitado 'version: 3.8' para evitar la advertencia de obsoleto
services:
  analytics:
    # 1. ESPECIFICAR EL CONTEXTO: Le decimos a Docker que busque archivos (como requirements.txt) 
    # en la carpeta superior ('..', que es Big-Daddy)
    build:
      context: ..
      # 2. ESPECIFICAR EL DOCKERFILE: Le decimos dónde encontrar el Dockerfile real (en la carpeta actual, '.')
      dockerfile: Dockerfile 
    
    container_name: finplus_analytics_container
    ports:
      # Mapeo de puertos CRÍTICO: 8888 del host a 8888 del contenedor
      - "8888:8888" 
    volumes:
      # Mapear su carpeta de trabajo al /app dentro del contenedor
      - ../:/app