version: '3.8'

services:
  analytics:
    # Asegúrese de que el nombre del build apunte a su Dockerfile
    build: . 
    container_name: finplus_analytics_container
    ports:
      # Mapeo de puertos CRÍTICO: 8888 del host a 8888 del contenedor
      - "8888:8888" 
    volumes:
      # Mapear su carpeta de trabajo al /app dentro del contenedor
      - ../:/app 
    # Comando para anular si es necesario, pero CMD es mejor en el Dockerfile
    # command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root