services:
  finplus_analytics:
    # IMPORTANTE: Cambiamos el contexto a '..' (la carpeta superior/raíz)
    # Esto permite a Docker encontrar 'requirements.txt' y la carpeta 'docker/'
    build:
      context: ..
      # Como el contexto ahora es la raíz, especificamos la ruta al Dockerfile
      dockerfile: docker/Dockerfile

    # Sincroniza las carpetas de su PC con el contenedor
    volumes:
      - ../:/app

    # Publica el puerto 8888 para acceder a JupyterLab desde su navegador
    ports:
      - "8888:8888"

    container_name: finplus_analytics_container

    tty: true