services:
  finplus_analytics:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    volumes:
      - ../:/workspace   # evita sobrescribir /app

    ports:
      - "8888:8888"

    container_name: finplus_analytics_container
    tty: true
